baseurl: "https://wizards.podops.dev/"
languageCode: 'en-us'
title: "Do Wizards dream of magic sheep?"
theme: "wizards"
paginate: 10
paginatePath: "page"

params:
  contact: "hellp@txs.vc"
  logo: false
  sidebar: true
  
  podcast:
    title: "Do Wizards dream of magic sheep?"
    description: "See what happens when an artificial wizard starts to dream of wizards, magical creatures and sometimes moving stairs. This is an artificial, AI-generated podcast."
    category:
      name: Fiction
      subcategories: ['Fantasy']
    explicit: true
    author: ArtificalWizard
    owner:
      name: Transformative Services
      email: hello@txs.vc
    cdn: https://storage.googleapis.com/cdn.podops.dev
    local: false
